/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5f5f9532-fab1-4682-b034-188b83166bad",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SHbC1wpOM",
    "aws_user_pools_web_client_id": "5lnnhfs9g4dinmeej6ccsvnt0h",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_mobile_analytics_app_id": "9f0927cd93ec4dac9b602ddda051be7a",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "cdedashboardapi",
            "endpoint": "https://g6yemt9011.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
