/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:550a32a7-4332-484e-a8fc-303a1b0522e0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gQcZbEVCt",
    "aws_user_pools_web_client_id": "2bi35rf3r73o35h24jovbmk2d4",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_mobile_analytics_app_id": "28e217bc49524629b70d22309590ef27",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "twittercovid",
            "endpoint": "https://v0jthppmtj.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;